### PR TITLE
Add One click Shiny Pokémon Raid

### PR DESCRIPTION
**Pull request by ppllouf**
Add One click Shiny Pokémon Raid

Wi-Fi mode, game needs to be saved and restarted to take effect.

Please improve the addition of other languages.
Due to my use of the Chinese system, I am unable to display characters correctly.

### CODE REVIEW

**Comment by wubinwww** [comment]
Replace archived inactive seeds with random Black5 and Black6 heterochromatic seeds, without replacing existing active pits. Once a popular feature in the Chinese modification industry, we hereby guarantee the legality of the network connection.

**Comment by wubinwww** [comment]
The full map Riad replaces the archived inactive Riad with random Black5 and Black6 heterochromatic seeds, and does not replace the existing active Riad. At one time, it was a popular function in the refitting field in China, and the legality of network connection is hereby guaranteed.

**Comment by Manu098vm** [comment]
Thank you for the contribution. I'll take some time to review it and eventually merge to the main branch.


In the meanwhile, I gotta ask, what's the reason for excluding the Distribution raids to be shiny with this one-click tool?
We can easily check if an Encounter is Shiny locked to prevent seed editing on those raids, but for standard (non-locked) distributions i'd say we can safely edit the seed to make the resulting Pokémon to be Shiny.

**Comment by ppllouf** [comment]
The inspiration for this feature comes from copy to other raids in PKHeX.
We can use this feature to restart the game once. Experience the unknown shiny Pokémon raid on the entire map.
This will greatly enhance the fun of playing games with friends and the fun of this plugin.

**Pull request merged**
